### ISSUE TITLE
Attack power for yellow and blue Deathly Wail is incorrect

### ISSUE THREAD

**Issue by JohnColvin** [fabrary/fab-cards#15]
The attack power for yellow and blue Deathly Wail is set as 6 right now, but should be 5 and 4.

You can see this in effect by searching fabrary for `st:attack c:runeblade talent:shadow power:6`.

Thanks for maintaining this, it was very helpful for printing paper proxies to test the new cards! ❤️

**Comment by manwaring** [comment]
Thanks so much for the heads up on this!  I've updated the library, the site should be up to date in a few minutes
